<a href="https://colab.research.google.com/github/pranavsrinivas29/data_analysis/blob/main/Pandas4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import drive

In [2]:
# from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [11]:

df=pd.read_csv('/content/drive/MyDrive/survey_results_public.csv')

In [7]:
# Data Analysis
statistics = df.describe()

print(statistics)

         Respondent     CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs  \
count  88883.000000  5.594500e+04   5.582300e+04  64503.000000  49790.000000
mean   44442.000000  5.519014e+11   1.271107e+05     42.127197      5.084308
std    25658.456325  7.331926e+13   2.841523e+05     37.287610      5.513931
min        1.000000  0.000000e+00   0.000000e+00      1.000000      0.000000
25%    22221.500000  2.000000e+04   2.577750e+04     40.000000      2.000000
50%    44442.000000  6.200000e+04   5.728700e+04     40.000000      4.000000
75%    66662.500000  1.200000e+05   1.000000e+05     44.750000      6.000000
max    88883.000000  1.000000e+16   2.000000e+06   4850.000000     99.000000

                Age
count  79210.000000
mean      30.336699
std        9.178390
min        1.000000
25%       24.000000
50%       29.000000
75%       35.000000
max       99.000000

In [8]:
# Computing correlation matrix
correlation_matrix = df.corr()

# Computing covariance matrix
covariance_matrix = df.cov()

print("Correlation Matrix:")
print(correlation_matrix)
print("\nCovariance Matrix:")
print(covariance_matrix)

Correlation Matrix:
               Respondent  CompTotal  ConvertedComp  WorkWeekHrs  CodeRevHrs  \
Respondent       1.000000  -0.003357       0.002930    -0.004589   -0.005240
CompTotal       -0.003357   1.000000       0.039725     0.003074    0.061090
ConvertedComp    0.002930   0.039725       1.000000     0.013908   -0.021261
WorkWeekHrs     -0.004589   0.003074       0.013908     1.000000    0.021092
CodeRevHrs      -0.005240   0.061090      -0.021261     0.021092    1.000000
Age             -0.001829   0.016500       0.108268     0.019976   -0.022486

                    Age
Respondent    -0.001829
CompTotal      0.016500
ConvertedComp  0.108268
WorkWeekHrs    0.019976
CodeRevHrs    -0.022486
Age            1.000000

Covariance Matrix:
                 Respondent     CompTotal  ConvertedComp   WorkWeekHrs  \
Respondent     6.583564e+08 -6.315381e+15   2.136238e+07 -4.394191e+03
CompTotal     -6.315381e+15  5.375714e+27   8.274954e+17  7.958632e+12
ConvertedComp  2.136238e+07  8.274954e+17   8.074253e+10  1.393028e+05
WorkWeekHrs   -4.394191e+03  7.958632e+12   1.393028e+05  1.390366e+03
CodeRevHrs    -7.421541e+02  2.599908e+13  -3.060372e+04  4.339906e+00
Age           -4.311388e+02  1.005163e+13   2.492512e+05  6.321487e+00

                 CodeRevHrs           Age
Respondent    -7.421541e+02 -4.311388e+02
CompTotal      2.599908e+13  1.005163e+13
ConvertedComp -3.060372e+04  2.492512e+05
WorkWeekHrs    4.339906e+00  6.321487e+00
CodeRevHrs     3.040343e+01 -9.442122e-01
Age           -9.442122e-01  8.424285e+01

<ipython-input-8-b0f68e8b26b6>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = df.corr()
<ipython-input-8-b0f68e8b26b6>:5: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  covariance_matrix = df.cov()

In [12]:
# Creating a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Charlie'],
        'Subject': ['Math', 'Math', 'Math', 'Science', 'Science', 'Science'],
        'Score': [85, 90, 88, 92, 89, 94]}
df1 = pd.DataFrame(data)

# Creating a pivot table
pivot_table = df1.pivot_table(index='Name', columns='Subject', values='Score', aggfunc='mean')

print("Pivot Table:")
print(pivot_table)

Pivot Table:
Subject  Math  Science
Name
Alice      85       92
Bob        90       89
Charlie    88       94

In [13]:
df.head(2)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [15]:
pivot_table2 = df.pivot_table(index='Employment', columns='Country', values='Age', aggfunc='mean')
pivot_table2

Country,Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,...,United Kingdom,United Republic of Tanzania,United States,Uruguay,Uzbekistan,"Venezuela, Bolivarian Republic of...",Viet Nam,Yemen,Zambia,Zimbabwe
Employment,,,,,,,,,,,,,,,,,,,,,
Employed full-time,30.071429,25.250000,31.264706,NaN,35.0,NaN,31.693642,25.822581,33.310698,30.914405,...,32.354888,31.545455,33.455786,30.590361,27.578947,28.081081,28.324324,26.800000,26.250000,29.117647
Employed part-time,23.666667,24.000000,32.200000,NaN,22.0,NaN,28.058824,21.000000,26.141304,27.174312,...,28.000000,28.000000,24.158078,22.000000,21.800000,23.000000,24.222222,33.000000,26.000000,22.666667
"Independent contractor, freelancer, or self-employed",25.000000,29.714286,27.615385,50.0,NaN,NaN,33.063158,27.428571,38.673077,33.061728,...,37.494585,26.909091,36.997028,35.800000,29.800000,33.913043,27.764706,29.000000,26.333333,29.571429
"Not employed, and not looking for work",NaN,17.000000,21.666667,19.5,NaN,NaN,18.555556,27.000000,21.596491,19.000000,...,19.997768,NaN,19.429476,17.500000,NaN,19.600000,18.727273,NaN,36.000000,25.000000
"Not employed, but looking for work",19.500000,21.250000,23.300000,23.0,23.0,NaN,24.541667,25.800000,25.121622,21.928571,...,25.105960,24.333333,27.651887,24.500000,19.000000,22.583333,24.882353,26.333333,26.000000,23.666667
Retired,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,63.600000,66.333333,...,68.000000,NaN,66.264957,NaN,NaN,NaN,NaN,NaN,NaN,NaN